# Generated by Django 4.2.24 on 2026-02-05 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_input", models.TextField()),
                ("final_output", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="conversations.conversation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunOutputArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("chart", "Chart (JSON)"),
                            ("table", "Data Table (JSON)"),
                            ("text", "Text Summary"),
                            ("pdf_report", "PDF Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="output_artifacts",
                        to="runs.run",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunInputFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Document"),
                            ("image", "Image"),
                            ("text", "Text Summary"),
                            ("csv", "CSV File"),
                            ("excel", "Excel File"),
                            ("word", "Word Document"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_files",
                        to="runs.run",
                    ),
                ),
            ],
        ),
    ]
